title:            Nurul Imam
description:      It's me...
logo:             nurulimam.jpg
disqus_shortname: nurulimam
#Comment out url when working locally to resolve base urls correctly
url:              http://blog.nurulimam.com

# Owner/author information
owner:
  name:           Nurul Imam
  avatar:         profile.jpg
  email:          me@nurulimam.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        nurulimamnotes
  facebook:       nurulimamnotes
  github:         nurulimamnotes
  stackexchange:  
  linkedin:       nurulimam
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    NurulImamdotcom

# Analytics and webmaster tools stuff goes here
google_analytics: UA-21079145-1
google_verify: rfBNj_XP7uggJtI7p-el34qFKSG5NyhWQEDoFcyN1Ww
bing_verify: 650CD26DD3C1D889BE85188A9E77E478  

# Links to include in top navigation
# For external links add external: true
links:
  - title: Beranda
    url: /
  - title: Arsip
    url: /arsip
  - title: Tentang
    url: /tentang
  - title: Curriculum Vitae
    url: /cv

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Jakarta
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:title.html
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]
